apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: webapps
subjects:
- namespace: webapps
  kind: ServiceAccount
  name: jenkins
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io