apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecret
  annotations:
    kubernetes.io/service-account.name: jenkins


run below command to view the secrets

kubectl -n webapps describe secret mysecret